name: Build and Release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
      - name: Set reusable strings
        id: strings
        shell: bash
        run: |
          echo "libpico-dir=${{ github.workspace }}/libpico" >> "$GITHUB_OUTPUT"
          echo "libpico-build-dir=${{ github.workspace }}/libpico/build" >> "$GITHUB_OUTPUT"
          echo "picoparser-dir=${{ github.workspace }}/picoparser" >> "$GITHUB_OUTPUT"
          echo "native-lib-dir=${{ github.workspace }}/picoparser/src/picoparser/_native" >> "$GITHUB_OUTPUT"

      - uses: actions/checkout@v6
        with:
          repository: kiki-i/libpico
          submodules: recursive
          path: ${{ steps.strings.outputs.libpico-dir }}

      - name: Install Clang (Windows)
        if: matrix.os == 'windows-latest'
        uses: egor-tensin/setup-clang@v2

      - name: Configure CMake
        run: >
          cmake -B ${{ steps.strings.outputs.libpico-build-dir }}
          -S ${{ steps.strings.outputs.libpico-dir }}
          -G Ninja -DCMAKE_BUILD_TYPE=Release

      - name: Build libpico
        run: |
          ninja -C ${{ steps.strings.outputs.libpico-build-dir }}

      - uses: actions/checkout@v6
        with:
          path: ${{ steps.strings.outputs.picoparser-dir }}

      - name: Move libpico (Linux)
        if: matrix.os == 'ubuntu-latest'
        run: |
          mkdir ${{ steps.strings.outputs.native-lib-dir }}
          mv ${{ steps.strings.outputs.libpico-build-dir }}/*.so ${{ steps.strings.outputs.native-lib-dir }}

      - name: Move libpico (Windows)
        if: matrix.os == 'windows-latest'
        shell: pwsh
        run: |
          mkdir ${{ steps.strings.outputs.native-lib-dir }}
          mv ${{ steps.strings.outputs.libpico-build-dir }}/*.dll ${{ steps.strings.outputs.native-lib-dir }}

      - uses: actions/setup-python@v6
      - name: Build wheels
        run: |
          cd ${{ steps.strings.outputs.picoparser-dir }}
          python -m pip install --upgrade build
          python -m build

      - name: Upload wheels
        uses: actions/upload-artifact@v6
        with:
          name: build-artifacts-${{ matrix.os }}
          path: ${{ steps.strings.outputs.picoparser-dir }}/dist/*

  release:
    needs: build
    runs-on: ubuntu-slim
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v7
        with:
          path: artifacts

      - name: Create GitHub release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: ${{ github.ref_name }}
          files: artifacts/**/*.whl
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
